### ISSUE TITLE
Link at the bottom of the legislation page.

### ISSUE THREAD

**Issue by AceTylerCholine** [chrisflesher/rcvfortexas#20]
Link at the bottom of the legislation page is hard to see

**Comment by AceTylerCholine** [comment]
> @AceTylerCholine The link really is hard to see! So much so that I'm not sure which one you're talking about. Could you provide a screenshot or share the link text? If you can I'll try to make it more visible.

It's the "survey" link as highlighted in the attached picture. Thanks @ironunicorn 

![Screenshot 2021-09-01 221713](https://user-images.githubusercontent.com/44661062/131776157-954f3ee0-82e3-4ef1-adc8-79c34c71a1f4.png)

**Comment by ironunicorn** [comment]
@chrisflesher So I looked into this and the reason we're not seeing an underline for this link is because all anchor tags on the website have `text-decoration: none;` applied (line 326 in theme.scss).  If I edit that file it would mess up the styling for all the other links on the website.  If we wanted to be sticklers I'd recommend we shift all those css type selectors to class selectors, but it's probably not worth the effort.  

The easy thing to do would be to just add an inline style to that specific anchor tag in the content source code on the [nationbuilder website](https://rcvfortexas.nationbuilder.com/admin/sites/1/pages/50/basic/edit).

This content doesn't appear to be in the github code so I don't think I can make a pull request for this change. Are you okay with me updating the website directly?

**Comment by chrisflesher** [comment]
Yes, go ahead and update the website directly! Nice work figuring this out.

**Comment by ironunicorn** [comment]
Okay! I've updated the content. @AceTylerCholine Please let me know if you'd like to see any other style tweaks.

![Screen Shot 2021-09-03 at 2 07 57 PM](https://user-images.githubusercontent.com/11695752/132055026-a6138505-9076-4f72-8cba-d2a70aac6da5.png)

**Comment by chrisflesher** [comment]
Seems like this is resolved.
