### ISSUE TITLE
Replace volunteer categories on website with Action Sign-Up Form.

### ISSUE THREAD

**Issue by hwasserstrum** [chrisflesher/rcvfortexas#22]

**Comment by chrisflesher** [comment]
From Harriet: can we just include a link to the form instead of listing volunteer categories on the website?

**Comment by ironunicorn** [comment]
@chrisflesher I'd like to help out with this issue, but I'm not exactly sure which volunteer categories or which form you're talking about. There's the [https://www.rcvfortexas.org/volunteer_1](https://www.rcvfortexas.org/volunteer_1) page, but that's a form with categories. Do you want the categories removed from that form or moved somewhere else?

**Comment by chrisflesher** [comment]
I am assuming @hwasserstrum has a Google Form that she'd like to use instead of the webpage volunteer form. I am guessing there is a tradeoff with ease of customization vs. ease of database entry. @hwasserstrum do you have an example of a form?

**Comment by hwasserstrum** [comment]
This is the Form: https://docs.google.com/forms/d/1MPIE12tL6raTShMYXKAPgNKEPYdxgXNqLCBsXglg4qk/edit?edit_requested=true. My thought is that by linking to the form instead of providing a list on the website we can have more specific volunteer options that we can easily update. What do you think?

    On Sunday, August 29, 2021, 03:33:17 PM CDT, chrisflesher ***@***.***> wrote:  
 
 


I am assuming @hwasserstrum has a Google Form that she'd like to use instead of the webpage volunteer form. I am guessing there is a tradeoff with ease of customization vs. ease of database entry. @hwasserstrum do you have an example of a form?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ironunicorn** [comment]
Thanks for clarifying, @hwasserstrum 

So, yes, it's just like Chris said. It's possible to link to your google form and then periodically [import responses](https://support.nationbuilder.com/en/articles/3021365-import-people) into nation builder for email capabilities. You can also just continue to [add to your custom field](https://support.nationbuilder.com/en/articles/2362823-create-custom-people-fields) in your nation builder form directly, but then it looks like if you add a new field the github code needs to be updated too if you want it to appear in the form, correct?  

As is, the code is flexible enough to automatically accommodate new volunteer types if you just add to the same field. It's also possible to make the code flexible enough to handle any new fields you desire (I'd want to have a quick chat with you to define requirements if you wanted to go this route).

Personally, I don't love the idea of shifting to google forms because you're creating work for yourself in perpetuity with the manual importing and because it just looks slightly less professional. You should definitely take my opinions with a grain of salt though because I don't have any experience with non-profit organizations.

If you'd like to keep things in nation builder, give me a couple times when you're available for a 15 minute call. Otherwise let me know if you'd like the google form and I'll go about adding the link.

**Comment by hwasserstrum** [comment]
I'd appreciate an explanation and a recommendation. If you are ok talking on Labor Day, pick any time and let me know. If not, please suggest any time after 3pm on Wednesday or after 1pm on Thursday.ThanksHarriet
    On Sunday, September 5, 2021, 03:47:22 PM CDT, Irene Foelschow ***@***.***> wrote:  
 
 


Thanks for clarifying, @hwasserstrum

So, yes, it's just like Chris said. It's possible to link to your google form and then periodically import responses into nation builder for email capabilities. You can also just continue to add to your custom field in your nation builder form directly, but then it looks like if you add a new field the github code needs to be updated too if you want it to appear in the form, correct?

As is, the code is flexible enough to automatically accommodate new volunteer types if you just add to the same field. It's also possible to make the code flexible enough to handle any new fields you desire (I'd want to have a quick chat with you to define requirements if you wanted to go this route).

Personally, I don't love the idea of shifting to google forms because you're creating work for yourself in perpetuity with the manual importing and because it just looks slightly less professional. You should definitely take my opinions with a grain of salt though because I don't have any experience with non-profit organizations.

If you'd like to keep things in nation builder, give me a couple times when you're available for a 15 minute call. Otherwise let me know if you'd like the google form and I'll go about adding the link.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ironunicorn** [comment]
Harriett and I chatted and came up with a way forward: 

We're going to keep things in nationbuilder, but we're going to divide up the volunteer types into categories so it's easier to look at a longer list of checkboxes.  In order for this to work, the tags will have to follow a naming convention of `category - specific volunteer opportunity`. Each `category` will be displayed above a list of corresponding `specific volunteer opportunities`.  I'll be in charge of making the tags from the list in the action form that aren't already in nationbuilder and updating the tags already in there to follow the new naming convention.

**Comment by ironunicorn** [comment]
@hwasserstrum [here's](https://rcvfortexas.nationbuilder.com/admin/sites/1/themes/5dabb2094445ea66232bca7e/preview?browser_id=default&logged_in=0&page_id=46) what I have so far. DO NOT HIT THE PUBLISH BUTTON.

Obviously, the categories will change, but for now I wanted to make it so they still looked reasonable on the current website. I kept the styling super simplistic because I'm not good at designing things, but I'm happy to take direction. Please let me know what you'd like to see and I'll style it before making a pull request.

**Comment by hwasserstrum** [comment]
Printed below is what you included with my suggested changes in red. Hope this is not too much for the website page.ThanksHarriet
Live Outreach  Research events  Gather signups at future eventsSupporter Outreach
 Make calls to new supporters

Personal Outreach

 Host a virtual or live event house party

Communications

 Post to social media

 Write Letters to the Editor
 Develop content for website or other communications  Train to be a speaker
Local Chapter
 Form or join a local chapter  Request RCV speaker
  Outreach to local organizations and/or media   Outreach to local jurisdictions and/or elected officials
Offer a skill

 Fundraising

 Communications

 Graphics

 Data analysis
 Legal Technology

    On Tuesday, September 7, 2021, 04:22:28 PM CDT, Irene Foelschow ***@***.***> wrote:  
 
 


@hwasserstrum here's what I have so far. DO NOT HIT THE PUBLISH BUTTON.

Obviously, the categories will change, but for now I wanted to make it so they still looked reasonable on the current website. I kept the styling super simplistic because I'm not good at designing things, but I'm happy to take direction. Please let me know what you'd like to see and I'll style it before making a pull request.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ironunicorn** [comment]
@hwasserstrum Confirming the changes are live and that I've updated the website to include all the options from the action signup form you shared. Please let me know if anything needs changing.

**Comment by hwasserstrum** [comment]
Thanks for doing this -- it looks great. Here are two minor changes:Please add under Live Outreach - Gather signups at future events.Please delete under Messaging Team -  Design graphic template for presentations and meeting agendas.Thanks
Harriet
    On Sunday, September 12, 2021, 12:08:23 PM CDT, Irene Foelschow ***@***.***> wrote:  
 
 


@hwasserstrum Confirming the changes are live and that I've updated the website to include all the options from the action signup form you shared. Please let me know if anything needs changing.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ironunicorn** [comment]
Okay, updated!

**Comment by hwasserstrum** [comment]
thanks!
    On Monday, September 13, 2021, 06:18:42 AM CDT, Irene Foelschow ***@***.***> wrote:  
 
 


Okay, updated!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chrisflesher** [comment]
It looks like this is working on the website.
