### ISSUE TITLE
Implement email capability from rcvfortexas.org

### ISSUE THREAD

**Issue by hwasserstrum** [chrisflesher/rcvfortexas#23]

**Comment by chrisflesher** [comment]
Work with Kathryn to set up e-mail addresses

**Comment by ironunicorn** [comment]
I looked into this issue and messaged Kathryn with my findings in slack. Essentially, we need to set up google workspace (which should be free for nonprofits) and then link that with the domain. I recommend that someone higher than me in the organization do this because whoever sets this up will have a lot of administrative power: https://www.google.com/nonprofits/ 

The setup should be fairly straight forward, but I'd be happy to hop on a call to help if there are any questions.

Let me know if this helps or if I can do anything else here.

**Comment by chrisflesher** [comment]
Thanks for the info! We signed up for Google non-profits today, hopefully in 2-14 business days we will get notification if we've been approved.

**Comment by chrisflesher** [comment]
We got accepted to Google for Nonprofits and set up some initial e-mail accounts.

**Comment by hwasserstrum** [comment]
Thanks! Emails are working. Are you going to set up the Google drive or is it already set up and we just need to know how to access it?

**Comment by chrisflesher** [comment]
This is already set up, you just need to go to drive.google.com and in the top right corner select your harriet.wasserstrum@rcvfortexas.org account. There is nothing on the drive right now, we'll need to create shared folders and move stuff from the other google drive sites. Will make a new issue for this.
