### ISSUE TITLE
Delete unsubscribed and people with no email or phone from NationBuilder

### ISSUE THREAD

**Issue by hwasserstrum** [chrisflesher/rcvfortexas#71]
We pay for NationBuilder based on number of people on the website. I'd like to periodically delete everyone who has unsubscribed but save their information someplace where we can access it if there is a reason to do so in the future.

**Comment by hwasserstrum** [comment]
Also delete all records added when someone on FB likes us or someone on Twitter follows us. I just changed the default setting so new records won't be added going forward.

**Comment by ghost** [comment]
Happy to help with this. I have an account on the NB site (username = austinbegin), but I guess I'm missing some permissions.

**Comment by chrisflesher** [comment]
Hey Austin, you should have permissions now.

**Comment by ghost** [comment]
Indeed I do. I will get to work on this. I will create a spreadsheet in the shared Google Drive for the Tech team to put the removed people, either for opting out, missing contact info, or interacting with social media.

**Comment by ghost** [comment]
I created a list in NB called "social_media_people_to_remove" and cross-checked it to make sure to volunteers were not removed. The list contains those added to the database from Facebook and Twitter. An admin will need to go into the list settings and click "Delete people from nation" next.

**Comment by chrisflesher** [comment]
Backed up the database and deleted the list you made, thanks!

**Comment by hwasserstrum** [comment]
How do I access the list of people who were deleted?

**Comment by chrisflesher** [comment]
They're on the GDrive here:
https://docs.google.com/spreadsheets/d/19095gHdq2nEWbqjHNTsIqAzjv3e7hazjMXLWbZdbb_w/edit#gid=0

**Comment by ghost** [comment]
Thanks, Chris. I still need to go through those without emails/phone numbers and those opted out of communication, so this is issue is technically not completed yet.

**Comment by ghost** [comment]
The "people_to_remove" list in NB now has those who only have an email but are opted-out of communication or the email is bad as well as some more social media stragglers. They have once again been saved in the Google Drive spreadsheet. Let me know if any other groups need to be filtered out. Not sure if we are keeping those who only have phone numbers yet opted-out of texts.

**Comment by hwasserstrum** [comment]
I would like to understand the parameters you used. The first group I wanted removed but saved was those who unsubscribed. There were 286 of them on a file I downloaded on 4/4/22. The second group I wanted totally deleted were people with both no email and no phone number. I think all oof those people had records set up when they liked us on Facebook or Twitter. There were probably about 1500 of them but I don't have a recent file from which I can tell.  

The list you created of "people to remove" has 175 people, most but not all of whom unsubscribed. How were those names selected? You said you included people with bad emails and some social media stragglers. What selection did you use to get the large export you did with 3568 lines?
Thanks
Harriet

**Comment by ghost** [comment]
I used this filter to find the social media stragglers. The first group that was removed was using a different filter that somehow missed these 69 people that are included in the 175. Those people removed earlier did not have any phone or email info but definitely were added via social media. Those removed are in the Google Drive linked above (first page).
![Criteria3](https://user-images.githubusercontent.com/91707175/172027904-56f9e2c7-d9bb-45fa-96c3-7bb02afef5ab.PNG)

The 175 group was created using this filter:
![Criteria2](https://user-images.githubusercontent.com/91707175/172027959-a1d0eb3c-2929-4123-aada-27a2fa734d7f.PNG)

The 3568 group was created using this filter but I only exported them and ended up not doing anything else with it because  some actual active people might have been included in it:
![Criteria1](https://user-images.githubusercontent.com/91707175/172027974-3e14867f-7bb0-4c84-9834-4e764e84bd5a.PNG)

If I include those who only have a phone number and opted out of texts, the filtered group number may be a little bit closer to what you are estimating. Here's what that looks like:
![Criteria4](https://user-images.githubusercontent.com/91707175/172028238-48c4c0d8-d2ba-4610-9a9a-6f1752c1abdf.PNG)

**Comment by hwasserstrum** [comment]
Thanks, this helps. Your file of People Removed (N=916) looks good. Please take the 68 "stragglers" on your People to Remove list off NB and add them to the People Removed file. While I initially wanted the Unsubscribed taken off of NB so we wouldn't have to pay for them, let's leave those 290 unsubscribed on NB for now as we are dealing with costs due to a large file we just imported for a texting campaign. 
Thanks, Harriet

**Comment by ghost** [comment]
Done. The 69 are ready to be removed when ready. They are in the people_to_remove list in NB.

**Comment by hwasserstrum** [comment]
Thanks for picking up the social media stragglers to delete and adding them to the People Removed document in our Google Drive.
    On Tuesday, June 7, 2022, 10:53:20 AM CDT, austinbegin ***@***.***> wrote:  
 
 


Done. The 69 are ready to be removed when ready. They are in the people_to_remove list in NB.

**Comment by chrisflesher** [comment]
Ok, deleted these, thanks @austinbegin
