### ISSUE TITLE
Workflows Utilization

### ISSUE THREAD

**Issue by loraschafer** [chrisflesher/rcvfortexas#81]
This is a larger project to learn Nation Builder Workflows, establish a step-by-step procedure, and work with team leads/communications to implement automated email campaigns.

**Comment by miketbrand** [comment]
This issue has been determined to be a priority 1 (high priority) issue.

**Comment by dsgit215** [comment]
It looks like NationBuilder refers to "workflows" as "Paths."  Here's some support material I found:

https://support.nationbuilder.com/en/articles/2291117-create-a-path

https://support.nationbuilder.com/en/articles/3055899-create-paths

**Comment by miketbrand** [comment]
There are two different kinds of workflows within NationBuilder.  

Paths are one kind of workflow that focuses on manually engaging with supporters in order to funnel them into the efforts that best align to their level and type of interest.

The other type of workflow is automations which send out emails at predefined intervals to groups of people in NationBuilder and then track they're engagement with the messages that they've been sent.
