### ISSUE TITLE
Migrate From RankIt to RankedVote

### ISSUE THREAD

**Issue by miketbrand** [chrisflesher/rcvfortexas#84]
The RankIt application that RCVforTexas.org uses to demonstrate RCV use cases is no longer supported.  Since RankIt now refers its viewers to RankedVote instead, that is where we should be directing them initially.

**Comment by miketbrand** [comment]
This will involve the following tasks:

1. Replace RankIt examples with RankedVote examples. The link to the page with all of RankedVote's demos is: https://www.rankedvote.co/demo
2. Replace RankIt home page links with RankedVote home page link. The link to the RankedVote home page is: https://www.rankedvote.co/
3. Replace the RankIt logo with a RankedVote logo
4. Replace the RankIt "most important benefits of Ranked Choice Voting" link with the RankedVote "benefits of RCV" link. RankedVote benefits of RCV link: https://app.rankedvote.co/rv/df145v2x0ww8v113hi/vote
5. Add RankedVote "Republican Presidential Candidates" link. Republican presidential candidates link: https://app.rankedvote.co/rv/w327pidalxc5lnpdhz/vote



</body>

</html>

**Comment by dsgit215** [comment]
Updates have been made to the following pages.  If you have any questions or modifications, let me know.  - Debbie

https://www.rcvfortexas.org › rank_it_test_out_rcv
- Updated this page with RankedVote content and set up a redirect to the updated slug to /rankedvote-test-out-rcv
- I also added the Republican Presidential Candidate content and link to this page. 
- Since this page didn't previously have a meta/SEO description, I added one.
- Since this page is part of a section in Nationbuilder that's set up as an "FAQ", these updates also updated https://www.rcvfortexas.org/resources_for_you

https://www.rcvfortexas.org › rankit
- This looks like it was an old page that wasn't being used.  I deleted the page content and redirected the slug to /rankedvote-test-out-rcv.

https://www.rcvfortexas.org › what_is_rcv_1
- Removed RankIt content that was at the bottom of the page and replaced it with a reference and link to /rankedvote-test-out-rcv.  

https://www.rcvfortexas.org/rescources_1 
- This was an old, unused page that contained some RankIt content and was still in a published state.  I removed the page content and set up redirect to /resources_for_you
