### ISSUE TITLE
Revise Communication Preferences - (formerly - Make the Sign-Up Process Less Cumbersome) (P2)

### ISSUE THREAD

**Issue by miketbrand** [chrisflesher/rcvfortexas#91]
The sign-up was modified more than one year ago so google analytics could track new signups coming from social media. Ever since, it's been rather cumbersome.

**Comment by miketbrand** [comment]
Do we currently use a "Double Opt-in" or "Single Opt-in" [system](https://support.nationbuilder.com/en/articles/2344102-understanding-email-opt-ins-and-unsubscribe-links).  If it's double, we can potentially make the process a bit more user friendly by switching to single.

**Comment by dsgit215** [comment]
No, the system doesn't currently use a double opt-in, but it does have an "account activation" process that appears to be superfluous.   I'm currently doing some research on the various forms in use and the flows (automated and otherwise) that result when those forms are submitted.  (See my [Slack exchange](https://rankedchoicevotingtx.slack.com/archives/C03JQUADTDJ/p1696887212464589) with Harriet.) I'm going to wrap up some notes on my research and initial recommendations this week.  Will follow-up with Harriet, et al at that point.

**Comment by dsgit215** [comment]
See comments [here](https://github.com/rcvfortexas/rcvfortexas/issues/92#issuecomment-1773458731).

**Comment by dsgit215** [comment]
### Comprehensive List of All Changes Made Through 2023.11.04

**MISC OPT-IN REFINEMENT WHILE OTHER CHANGES WERE IN PROGRESS:**  
+ On https://rcvfortexas.nationbuilder.com/admin/sites/1/edit - Unchecked 'Email & text message opt-in checkbox defaults to checked'  (COMPLETED: 2023.10.25)

**REMOVAL OF USER (SUPPORTER) ACCOUNT ACTIVATION / ACCOUNT SETTINGS FROM SITE:**
+ On https://rcvfortexas.nationbuilder.com/admin/sites/1/pages/4/signup/edit - Unchecked 'Display account activation message after signing up'  **_===> ISSUE FOUND: When the account activation message is disabled, no acknowledgment message is being displayed on the site after form submission...even when acknowledgment content has been entered in the Signup settings field "After signing up, show this success message" (observed on Chrome and Firefox)_** (COMPLETED with Issue Noted: 2023.10.25)

+ On https://rcvfortexas.nationbuilder.com/admin/sites/1/pages/4/signup/mailing - Removed content in autoresponse email referring to account activation. (COMPLETED: 2023.10.25)

+ Removed "Sign in with..." content from the site footer by updating layout.html in the custom theme files on Dropbox as follows:
In the layout.html file, after these three lines

```
 </footer>
            <div class="footer-text-wrap">
              <div class="footer-text">
```

I removed the following lines:


 ```
               {% if request.logged_in? %}
                  <p>Hi <a href="{{ request.current_signup.settings_url }}">{{ request.current_signup.name_or_email }}</a>. View your
                  {% if site.show_public_profiles? %}
                    <a href="{{ request.current_signup.profile_url }}">public profile</a>,
                  {% endif %}
                  <a href="{{ request.current_signup.settings_url }}">account settings</a>, or
                  <a href="{{ request.current_signup.logout_url }}">sign out</a>.</p>
                {% else %}
                  <p>Sign in with <a href="{{ request.facebook_connect_url }}">Facebook</a>, <a
                      href="{{ request.twitter_connect_url }}">Twitter</a> or <a href="/login">email</a>.</p>
                {% endif %}
    
```
(COMPLETED: 2023.10.30) 

+   Removed "Sign in with..." content from the mobile menu by updating _nav.html in the custom theme files on Dropbox as follows:
In the _nav.html file, after these lines - 

```
  </li>
    {% endif %}
    {% endfor %}
  </ul>
```
I commented out the following - 

```
  {% comment %}
  {% unless request.logged_in? %}
  <div class="user-menu mobile-visible tablet-visible">
    <a class="login-button-facebook" href="{{ request.facebook_connect_url }}">Facebook</a>
    <a class="login-button-twitter" href="{{ request.twitter_connect_url }}">Twitter</a>
    <span>Or sign in with <a href="/login">email</a></span>
    <span>Don't have an account? <a href="/login">Register now</a></span>
  </div>
  {% endunless %}
  {% endcomment %}
```
(COMPLETED: 2023.10.30)           


**MISC UPDATE TO VOLUNTEER FORM AUTORESPONSE EMAIL CONTENT:**
+ On https://rcvfortexas.nationbuilder.com/admin/sites/1/pages/46/volunteer_signup/mailing - Augmented content with more information about other ways to get involved, etc.  (Used Sign Up autoresponse email as a model.) (COMPLETED: 2023.10.25)

**CHECKED DONATION FORM SETTINGS:**
+ Checked Donation Form settings for any content or other settings related to account activation.  None observed. (COMPLETED: 2023.10.25)

**REPLACED  HOMEPAGE EMAIL SIGNUP WITH CTA THAT LINKS TO FULL SIGN UP FORM:**
+Removed email sign up from homepage and replaced it with a CTA to the full sign up form as follows:
In the layout.html file, after these lines - 

 ```
<li>Next event: {{ event_page.event.local_start_at | date: '%A, %b. %-d' }}{% if event_page.event.is_multi_day? %} through {{ event_page.event.local_end_at | date: '%A, %b. %-d' }}{% endif %}. <a href="/calendar_2">View our events calendar.</a></li>
                  {% endfor %}
                </ul>
              </div>
              </div>

              {% if site.has_signup_page? %}
              <div class="bottom-content row-fluid">
```

I added the following line -

`<p>Join our email list! <a href="/sign_up">Sign up here</a>.</p> 
`

And I commented out the following - 

```
	{% comment %}          
		{% if request.sorta_logged_in? %}
                <div class="join-form">
                  <p>Hi <a href="{{ request.current_signup.settings_url }}">{{ request.current_signup.name_or_email }}</a>. View your
                  {% if site.show_public_profiles? %}
                    <a href="{{ request.current_signup.profile_url }}">public profile</a>,
                  {% endif %}
                  <a href="{{ request.current_signup.settings_url }}">account settings</a>, or
                  <a href="{{ request.current_signup.logout_url }}">sign out</a>.</p>
                </div>
                {% else %}
                <div class="join-text">
                  Join our email list: 
                </div>
                <div class="join-form span6">{% include "signup_form" with site.signup_page %}</div>
                {% endif %}
  		{% endcomment %}
```
(COMPLETED: 2023.10.30)

**CONSENT SUBJECT & FORM BACKEND SET-UP & ACTIVATION:**
+ On https://rcvfortexas.nationbuilder.com/admin/consent_subjects - Created the following Consent Subjects:
    + Newsletters (email)
    + Action Alert Emails
    + Action Alert Texts
    + Meeting & Event Email notifications
    + Meeting & Event Text notifications
    + Address for Legislator ID
    (UPDATED: 2023.11.04)

+ On https://rcvfortexas.nationbuilder.com/admin/consent_forms - Created and published three consent forms:
    + optin-consent-form-all-v1 - This will be set as the "default" consent form in NB and when activated will override the generic email and text opt in checkboxes on Sign Up.....and other forms on the site (SEE NOTES BELOW REGARDING THE CONSENT-FORM-OVERRIDE),
    + comm-pref-mgt-all-v1B  (DO NOT USE comm-pref-mgt-all-v1) - This will be used as the main Communications Preferences Management page.  A link to this page will be added to the footer in the 'Basic Logo' email theme (and possibly in other locations).  NOTE:  This form does not include the 'Address for Legislator ID' consent subject because a consent form in this stand-alone context doesn't have home address fields.
   + consent-form-override - This is an empty consent form that can be used to override the default consent form on specific form pages. (More on where this is used below.)

      NOTE:    The consent subjects used in opti-consent-form-all-v1 and comm-pref-mgt-all-v1 should be kept in synch if/when the RCV for Texas broadcast comnmunication types change in the future. (Exception: The 'Address for Legislator ID' consent subject is not used in the 'comm-pref-mgt-all-v1B' consent form.)  To modify these forms, new forms must be created as previous forms cannot be edited once published.   

     (COMPLETED: 2023.11.04)

+ On https://rcvfortexas.nationbuilder.com/admin/sites/1/edit - I checked the box for "Ask for consent" and selected optin-consent-form-all-v1 as the default form.  Then,..
+ In the page settings for the Contact Us, Donate, and Volunteer pages, I checked the box for "Override default consent form" and selected 'consent-form-override' as the override form.  As noted above, 'consent-form-override' is a blank consent form, so it's function is simply to remove the full 'optin-consent-form-all-v1' component from these other pages.  
(COMPLETED: 2023.11.04)

**PEOPLE DATABASE - 'PRE-20231104' tag**
+ To identify records in the database that existed prior to the implementation of the new opt-in options, I tagged all records that existed as of the implementation with the tag 'PRE-20231104.'  This can be used filter reciepients for targeted re-permissioning campaigns. (COMPLETED: 2023.11.04)

**EMAIL FOOTER UPDATE IN BASIC LOGO CUSTOM THEME**
+Modified the footer in the Basic Logo custom email theme by updating the mailing_basic.html and mailing_basic.txt files in the custom theme files on Dropbox as follows:

After the "This email was sent to..." line, I added the liquid variable code for 'comm-pref-mgt-all-v1B' with link text that reads "Update communication preferences."  I also changed the text associated with the Unsubsribe link in the footer to simply read "Unsubscribe."

NOTE: 
     + The "Update communication preferences" link generated by the liquid variable code is tokenized.  Per NB support content at [https://support.nationbuilder.com/en/articles/2363000-how-to-run-a-re-permissioning-campaign#send-your-consent-form](https://support.nationbuilder.com/en/articles/2363000-how-to-run-a-re-permissioning-campaign#send-your-consent-form) , "...users will click the link to populate the form...and fill it out. The form will populate at a unique and private URL (the fancy word is tokenized URL). It is sent for the specific person the email is addressed to, this way no one else can come to this page and change anything.  _The link will expire 30 days from the email sent date._    
     **_+ ISSUE:  It is not possible to apply any specific styles to the "Update communication preferences" link generated by the liquid variable code.  Therefore, the link text associated with the liquid variable is a different color than other links in the email.  In an effort to "normalize" this, I've applied a similar color to the Unsubscribe link accompanies this line of content in the footer.  UNFORTUNATELY, the link color appears to render a little differently in the end result.     
     + ISSUE:  The updates made to the mailing_basic.txt file are similar, but I'm uncertain how the liquid variable code will render in a text email.  Since most people get html emails, I don't anticipate this will be a significant issue._**  

(COMPLETED with the two issues noted above: 2023.11.04

 
**UNSUBSCRIBE PAGE**
+ On https://rcvfortexas.nationbuilder.com/admin/subscription_management_page/settings/edit  - I added some content to the top of the Unsubscribe page.  NOTE: The bolded heading on this page is controlled by NB and cannot be changed other than changing the organization name.  Also, note that the Unsubscribe page will remain in place even when the Communications Preferences page (created using the consent form noted above) is implemented.  However, the Unsubscribe page will only provide a means for users to unsubscribe from ALL email communications.  The settings available to enable preferences on the Unsuscribe page will NOT be used as these preferences are controlled by the tagging system...not the consent subjects/forms system.   (Completed: 2023.11.04)


**POINT PERSON UPDATES**
+ The Point Person designated for the Sign Up and Donate pages has been changed to David Green.  (Harriet remais the point person on the Get Involved/Volunteer form page.)  (COMPLETED: 2023.11.04)

**Comment by hwasserstrum** [comment]
I don't think this is related so I added a new project to condense number of volunteer options on Take Action page.

**Comment by dsgit215** [comment]
I agree.  Thank you.

> I don't think this is related so I added a new project to condense number of volunteer options on Take Action page.

**Comment by hwasserstrum** [comment]
I found the appropriate website page so made the changes myself. However, I don't know how to close the issue :(

    On Saturday, November 4, 2023 at 02:45:56 PM CDT, Debbie Spalding ***@***.***> wrote:  
 
 


I agree. Thank you.


I don't think this is related so I added a new project to condense number of volunteer options on Take Action page.

**Comment by dsgit215** [comment]
While all of the changes discussed have been implemented as of 2023.11.04, I'm going to leave this issue open for the immediate term should any minor tweaks be needed.  Also, I am working on a presentation deck that can serve as documentation / training material.  Once that's complete, I'll close this issue.  

If anything beyond minor tweaks needs to be addressed, a new issue can be opened.

**Comment by dsgit215** [comment]
### SUMMARY OF UPDATES COMPLETED - AS WEBSITE VISITORS & NB USERS SEE THEM:

_NOTE: When viewing the website, please make sure you are logged out of NB. Alternatively, view the site in incognito mode._

- The **[Sign Up](https://www.rcvfortexas.org/sign_up) page** has been updated with the new communication opt-in choices.

- Communication opt-ins have been removed from the **[Donate (Legislative Advocacy)](https://www.rcvfortexas.org/donate), [Donate (Education & Outreach)](https://www.rcvfortexas.org/donate_3), [Contact Us](https://www.rcvfortexas.org/contact_us_1), and[ Volunteer](https://www.rcvfortexas.org/get_involved) forms**.  I did this because I felt that the opt-ins provided too much of a distraction from the primary purpose of these forms.  If, however, you want to include the full set of opt-ins, I can set that up.  ALTERNATIVELY, I could set these pages up with an opt-in for just the newsletter (or some other subset of communication types).  

- The **"Join our email list" form** on the [homepage](https://www.rcvfortexas.org/) has been removed and replaced with a CTA that links to the full Sign Up form.

- References to **account activation/account setting/profile/sign in/sign out** on the website and messages have been removed.

- A **Communication Preferences page** has been created that users will be able to access from a link in the **footer of email communications** generated using the **Basic Logo custom theme**.  (If the link needs to be added to any other email themes at this time, let me know.)  Screen caps here - 
![Email-Footer](https://github.com/rcvfortexas/rcvfortexas/assets/77990608/68d67a44-2c9a-4ffc-ab01-b95fe0bdded8)

![comm-preferences](https://github.com/rcvfortexas/rcvfortexas/assets/77990608/641a12d1-ea5a-4487-a67e-eba51607e43a)

NOTE:  The **"Update communication preferences" link is tokenized**, meaning that the link is sent for the specific person to whom the email is addressed.  This way no one else can come to this page and change anything. The link will expire 30 days from the email sent date.  Also, the code used to create the link in the footer, unfortunately, does not allow the link to be stylized - i.e. **the color of the link cannot be changed to match the color of other links in the email**.  In an attempt to "normalize" this to some degree, I've tried to change the link color of "Unsubscribe" to be the same.  However, I've noticed that different systems render this color differently, so it isn't always a true match. ☹️  You may also notice that the **"home address/legislator ID" item is not on the Communication Preferenes page**.  I had to remove it because when the consent form is used this way it only presents the name, email, and text fields.  (Thankfully, this is not the case when the the consent form is used in conjunction with the Sign Up, Donate and Volunteer forms.)

-  **[Unsubscribe](url)** has been updated with some intro content.  If this content needs to be revised for GitHub Issue #92, that is easy to do.  NOTE: Unfortunately, **the heading on the Unsubscribe page cannot be changed**  other than to modify the organization name.  ☹️

- In Nationbuilder, all records in the People database as of yesterday have been **tagged with "PRE-20231104."**  This will enable these records to be filtered for subsequent re-permissioning campaigns. 

- In Nationbuilder, David Green has been assigned as the **point person** for all records created via Sign Up and Donate.  Harriet remains the point person for all records created via the Volunteer form.

- In Nationbuilder, recipients for email and text communication blasts can be filtered based on combinations of criteria that now include "Consent" ....in addition to previously existing criteria such as tags.  Since most records currently in the database are identified based on tags, you'll want to be sure to apply the appropriate Boolean logic to get all the records you want for any particular communication.  

I think that covers it for now.  If you have any questions or comments, let me know.  I'll be working on the documentation/training deck later this month.

**Comment by dsgit215** [comment]
An initial draft of documentation/training for the internal RCV-TX team has been completed. It is located on the RCV-TX Drive [here](https://docs.google.com/presentation/d/11SwF9xZabAzRRUV50mbW13PdVtCHGSGcfdT3Tz6Mj4s/edit?usp=sharing).  As you will see in the material, I've noted that there are still some kinks to be worked out - including matters related to Unsubscribe, records entered manually, refinement of the filters used to identify recipients for various communications, etc.  I also want to add some content specifically for the Tech Team about how the consents for the various communication types  were set up in NationBuilder.  

I will be traveling for the next several weeks and don't anticipate being able to put solid time into following up on this until after the holidays.  NOTE: If anything urgent comes up during this time, I can be contacted via email (dspaldx@gmail.com) to try to address discrete matters.

**Comment by dsgit215** [comment]
Closing this issue.  Will open a new issue for major updates and for re-permissioning.
