### ISSUE TITLE
Give Folks the Option to Opt-Out of the Newsletter, but Still Support RCV (P1)

### ISSUE THREAD

**Issue by miketbrand** [chrisflesher/rcvfortexas#92]
New sign-ups (and people with established accounts) should be able to say they don't want to receive our monthly newsletter or meeting notices but still support RCV and we should contact them when we want them to take action with respect to supporting proposed legislation.

**Comment by hwasserstrum** [comment]
We should also customize our unsubscribe page so we give people options at the end as well as at the beginning.

**Comment by miketbrand** [comment]
So email blasts use tags to determine who all the email is being sent out to.  Therefore, the opt-out process works by removing tags from the People records that we have in NB.  I can tailor our Unsubscribe page to [allow unsubscribers to remove certain tags but not others](https://support.nationbuilder.com/en/articles/2362704-how-to-use-the-unsubscribe-page).

With that in mind, here's my plan.  I want to have at least two tags, one that is "RCV supporter" and the other that is "Receives emails".  The unsubscribe page will allow the unsubscribers to remove one or both tags from their record.

There are a few details that would need to be ironed out before I begin a process like that:

1. Do we already have tags in place that serve the aforementioned purposes?
2. If we already have such tags, do we have tags that we use to keep track of different email groups?  i.e. "This email is worded to target republican interests, so we're going to send it out to everyone with a 'Republican' tag."  If so, then I can make those listed options as well.
3. If these tags don't exist, then when I create the "RCV supporter" tag, who all should I give it to in our existing database?  Should we just assume that everyone is a supporter until they tell us otherwise?  Alternatively, I can create a [Survey](https://support.nationbuilder.com/en/articles/2306391-create-a-survey-page) page that we can use to let our supporters apply the tag to themselves based upon their responses.

**Comment by dsgit215** [comment]
2023.10.18 CORRECTION/UPDATE: The following quoted text has been updated in the next comment.

> NOTE:  In addition to "tags," there are other system designations associated with each database record.  For example, there is an "Opted-In" designation that is added to the record when a user selects "Send me...updates" on the Sign Up form or the Volunteer form.  (And as noted in a [comment on another Github issue](https://github.com/rcvfortexas/rcvfortexas/issues/91#issuecomment-1767473347), there is no double opt-in.)  Further, when the user Unsubscribes, that "Opted-In" designation is removed, but the user remains in the database.

**Comment by dsgit215** [comment]
UPDATE TO THE COMMENT ABOVE:

In addition to the "Opted-In" designation on the user's record, there are "Receive emails" and "Receive text messages" designations.  (See screen cap below showing the "Receive emails" designation.)  In the screen cap, you'll see it's unchecked, that is because I pulled up an old RCV email message this AM and unsubscribed using the link at the bottom.  (Note: The "Opted-In" designation on the record is still there, which seems a bit odd.  I'm going to look into this further.)

![image](https://github.com/rcvfortexas/rcvfortexas/assets/77990608/335c9766-61b7-4452-9961-4c5287a27018)

**Comment by dsgit215** [comment]
After another afternoon of research related to https://github.com/rcvfortexas/rcvfortexas/issues/91, I'm convinced that we need to coordinate efforts. I'm in the process of updating my initial research and waiting on a response from Nationbuilder on some questions I've had.  I'll follow up with both of you (@miketbrand & @hwasserstrum) within the next several days.  (We'll probably need to get on a Zoom call to have an interactive discussion.)

**Comment by miketbrand** [comment]
Interesting. NationBuilder allows us to specify a list of "tags" that we want to allow the unsubscribers to unsubscribe from.  At the end of that list, there's always an "unsubscribe all" option that we have no power to modify or get rid of.  It looks like the "Receive emails" field that you've pointed out is what that last "unsubscribe all" option effects.

![image](https://github.com/rcvfortexas/rcvfortexas/assets/11402727/e3d77dc6-a379-4356-bf6e-367fc9eec8cb)

**Comment by hwasserstrum** [comment]
Let me know when you want to meet.
    On Wednesday, October 18, 2023 at 05:17:02 PM CDT, Debbie Spalding ***@***.***> wrote:  
 
 


After another afternoon of research related to #91, I'm convinced that we need to coordinate efforts. I'm in the process of updating my initial research and waiting on a response from Nationbuilder on some questions I've had. I'll follow up with both of you ***@***.*** & @hwasserstrum) within the next several days. (We'll probably need to get on a Zoom call to have an interactive discussion.)

**Comment by dsgit215** [comment]
@miketbrand, @hwasserstrum - I'm unable to tag Harriett under issue https://github.com/rcvfortexas/rcvfortexas/issues/91, so I'm putting this here.  I decided to compile my findings and recommendations into a slide deck to facilitate a conversation.  I'll send an email shortly to the both of you to try to coordinate a time to talk.  In the meantime, here's a link to the [slide deck](https://docs.google.com/presentation/d/1wNGRMwKLedI-7ahUysTJhKvbn8eOnJqpRWkk0Ec6nI4/edit?usp=sharing).

**Comment by dsgit215** [comment]
@miketbrand - Since I needed to do a bunch of back/forth between the consent forms for the new opt-in and for communication preference mgt,...and the Unsubscribe page, I went ahead and updated the 'Unsubscribe' and 'Update Communication Preferences'links in the footer of the main email theme.  I also added some content to the top of the [Unsubscribe page](https://www.rcvfortexas.org/unsubscribe).  If you want modify some of that content, you can do that [here](https://rcvfortexas.nationbuilder.com/admin/subscription_management_page/settings/edit) .  PLEASE NOTE:  The liquid variable for the Communications Preferences form can't be used in this content, but I don't think that will be a major issue.  

With regard to the specifics of _this_ issue - i.e. opting out but still supporting, technically - in the People database - that is  already happening and will continue to happen.  If/how that needs to be addressed in content on the Unsubscribe page, I'm not sure....other than to perhaps say if you no longer want to be considered a supporter, contact us.  Just a thought... Perhaps some more clarity from @hwasserstrum on this would help.
