### ISSUE TITLE
Merge the "Take Action" Page and the "Volunteer" page

### ISSUE THREAD

**Issue by miketbrand** [chrisflesher/rcvfortexas#94]

**Comment by dsgit215** [comment]
I'll take this one.

**Comment by dsgit215** [comment]
The "Take Action" page and the"Volunteer" page have been combined under the slug /get_involved.  The previous "Take Action" page has been archived and re-directs have been updated accordingly.  Also...

Home page -  Since the content in the News block in the upper right has to be edited in the template, I created a redirect for the Volunteer link in that section to go to the new, combined page at /get_involved.

**Comment by dsgit215** [comment]
P.S. I also updated the volunteer link in the Sign Up (Join Us) autoresponse email and the link used for the Sign Up completion landing page.
